### ISSUE TITLE
refresh cli command fails with wrong URL

### ISSUE THREAD

**Issue by Ocupe** [spicywebau/craft-embedded-assets#190] opened 2021-11-09 15:04 UTC
#### Description
When I run the new command "php craft embeddedassets/refresh/all" to refresh the thumbnails, it works for most of the embedded videos, but for one I get the following error message and the program quits: 

```bash
 Refreshing <some-file>.json ... Error: Invalid url 'https://vimeo.com/478944985' (Status code 404)
```
Checking the URL in fact reveals that it is a 404 page. The strange thing is that the url in `<some-file>.json` is partially different to the one from the error message: `https://vimeo.com/478944985/f7a04a8315` (and it leads to a public video). It appears that the second part of the url path is missing.

#### Other information
- Embedded Assets version: 2.9.0
- Craft CMS version: Craft Pro 3.7.20

**Comment by ttempleton** [comment] 2021-11-26 07:51
I was unable to reproduce any issues with this video, but it's worth noting that [the refresh commands will make the request to the provider using the original URL from the embedded asset file](https://github.com/spicywebau/craft-embedded-assets/blob/2.9.0/src/console/controllers/RefreshController.php#L82), so it's unlikely that this is being caused by the Embedded Assets plugin. I'm going to close the issue, but I'd recommend setting up a basic module to listen for the [`BeforeCreateAdapterEvent`](https://github.com/spicywebau/craft-embedded-assets/blob/2.9.0/docs/events.md#beforecreateadapterevent) that is [triggered before Embedded Assets hands over to Embed](https://github.com/spicywebau/craft-embedded-assets/blob/2.9.0/src/Service.php#L110-L115), to see what URLs are being used. If it turns out that something is going wrong in Embedded Assets that's affecting that URL, we'll reopen the issue.

**Closed by ttempleton** 2021-11-26 07:51 UTC
