### ISSUE TITLE
Could not retrieve embed information (YoutTube).  after Update to 2.6.0

### ISSUE THREAD

**Issue by thomasbendl** [spicywebau/craft-embedded-assets#180] opened 2021-05-10 07:22 UTC
#### Description
After Update to Version 2.6.0 every YouTube Embed throws error "Could not retrieve embed information."
Vimeo works!

#### Steps to reproduce
1. https://www.youtube.com/watch?v=8Q_9h6VKm9c&t=457s
2. Could not retrieve embed information.
3. With Setting "Use YouTube nocookie?" enabled or not

#### Other information
- Embedded Assets version: 2.6.0
- Craft CMS version: 3.6.13

**Comment by ttempleton** [comment] 2021-05-10 07:39
Does the error persist if you enforce the Embed version `"embed/embed": "3.4.15"` in your site's `composer.json`?

**Comment by thomasbendl** [comment] 2021-05-10 07:49
What do you mean exactly. Changing "spicyweb/craft-embedded-assets": "2.6.0" to 3.4.15?

**Comment by ttempleton** [comment] 2021-05-10 08:07
Just released Embedded Assets 2.6.1 which requires Embed 3.4.15, no later version.  There weren't any changes in Embedded Assets 2.6.0 that should affect YouTube embeds, other than the nocookie setting -- but since the error occurs regardless of that setting, I think the error is being caused by a bug in Embed 3.4.16.  I'll close this issue now, but please let us know if the error persists with 2.6.1 and we'll reopen.

**Closed by ttempleton** 2021-05-10 08:07 UTC
