### ISSUE TITLE
Link to an asset in redactor field broken

### ISSUE THREAD

**Issue by payello** [spicywebau/craft-embedded-assets#149] opened 2020-10-23 15:30 UTC
#### Description
In version 2.2.5 this is working fine. But in version 2.3.1 it is broken. Essentially, there are JS errors and therefore I am not able to link to an asset in a redactor field

#### Steps to reproduce
1. Have a redactor field with the link button to `link to an asset`
2. When you try to add an asset it is not possible to attach to the text (the select button on the asset selection modal is disabled)
3.

#### Other information
- Embedded Assets version: 2.3.1 (also tried with latest version)
- Craft CMS version: 3.5.14

**Comment by ttempleton** [comment] 2020-10-25 13:24
Duplicate of #148.

**Closed by ttempleton** 2020-10-25 13:24 UTC
Labels: duplicate
