### ISSUE TITLE
Issue embedding YouTube videos: requestUrl() must be an instance of spicyweb\embeddedassets\models\EmbeddedAsset, null returned

### ISSUE THREAD

**Issue by daniellelecomte** [spicywebau/craft-embedded-assets#182] opened 2021-05-18 20:27 UTC
#### Description
Error when trying to add a new YouTube video to Assets in Craft:
`TypeError: Return value of spicyweb\embeddedassets\Service::requestUrl() must be an instance of spicyweb\embeddedassets\models\EmbeddedAsset, null returned`

#### Steps to reproduce
1. Navigate to Assets
2. Click on Embed button
3. Paste in YouTube URL
4. 500 error shows in console

#### Other information
- Embedded Assets version: 2.5.0
- Craft CMS version: 3.5.16
- Server is load balanced

**Comment by ttempleton** [comment] 2021-05-18 23:02
Closing this issue as a duplicate of #180.  If you're unable to upgrade to Craft 3.6 and Embedded Assets 2.6.1 at the moment, then you should follow the suggestion in https://github.com/spicywebau/craft-embedded-assets/issues/180#issuecomment-836305903 to enforce usage of Embed 3.4.15.

**Closed by ttempleton** 2021-05-18 23:02 UTC
