### ISSUE TITLE
update dependency on "embed/embed" to version v4.4 or higher

### ISSUE THREAD

**Issue by benedikte-vdw** [spicywebau/craft-embedded-assets#245] opened 2023-11-17 15:34 UTC
### Bug Description

I’m trying to do a plugin update, but get the error from the plugin oEmbed.

This is due to the fact that your plugin is currently using v.3.4.17, and the oEmbed plugin requires v.4.4. or higher.
Can you please update the composer requirements to use the latest version of embed/embed

### Steps to reproduce

1. have a Craft CMS install with Embedded Assets version 3.1.8
2. install plugin oEmbed v. 3.0.1 (url: https://github.com/wrav/oembed/blob/master/README.md) - latest version
3. results in error:
This is the error:
Performing update with Composer ... error: The command "'/usr/bin/php8.2' '/var/www/html/storage/runtime/composer.phar' 'update' 'wrav/oembed' '--with-all-dependencies' '--working-dir' '/var/www/html' '--no-scripts' '--no-ansi' '--no-interaction'" failed.
 
Exit Code: 2(Misuse of shell builtins)
 
Working directory: /var/www/html
 
Output:
================
 
 
Error Output:
================
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
 
  Problem 1
    - wrav/oembed 3.0.1 requires embed/embed ^v4.4 -> found embed/embed[v4.4.0, ..., v4.4.8] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires wrav/oembed 3.0.1 -> satisfiable by wrav/oembed[3.0.1].

### Expected behaviour

no errors

### Embedded Assets version

3.1.8

### Craft CMS version

4.5.11

**Comment by ttempleton** [comment] 2023-11-18 01:36
Closing this issue as a duplicate of #152.

There's some (fairly out-of-date) progress on an Embed 4 compatible version of Embedded Assets in the [`enhancement/embed-4`](https://github.com/spicywebau/craft-embedded-assets/tree/enhancement/embed-4) branch. That work stalled due to some Embed 3 functionality that was not included in Embed 4. I'm unsure if Embed 4 is still missing that functionality; I'm hoping to figure out a path forward one way or the other for a Craft 4 release (whether that involves working on pull requests or forking the project for the functionality we need), but unlikely to have time to look at it in the next couple of weeks.

**Closed by ttempleton** 2023-11-18 01:36 UTC
Labels: bug
