### ISSUE TITLE
GraphQL: "EmbeddedAsset" is not a possible type for "EmbeddedAssetInterface"

### ISSUE THREAD

**Issue by mheob** [spicywebau/craft-embedded-assets#157] opened 2021-01-27 12:56 UTC
### Description

I get the error `Runtime Object type \"EmbeddedAsset\" is not a possible type for \"EmbeddedAssetInterface\".` every time I try to get my embedded assets via GraphQL. Furthermore, I should say directly that I am using Craft CMS 3.6 with PHP 8.

```graphQL
{
  asset(id: 1475) {
    embeddedAsset {
      title
    }
  }
}
```

```json
{
  "errors": [
    {
      "debugMessage": "Runtime Object type \"EmbeddedAsset\" is not a possible type for \"EmbeddedAssetInterface\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "asset",
        "embeddedAsset"
      ]
    }
  ],
  "data": {
    "asset": {
      "embeddedAsset": null
    }
  }
}
```

#### Other information
- Embedded Assets version: `2.4.5`
- Craft CMS version: `3.6.0.1`
- PHP version: `8.0.1`

**Comment by nickroberts** [comment] 2021-01-28 05:14
I get the same thing. This looks like a very promising module, but if I can't use it with GraphQL, we aren't gong to be able to use it, unfortunately.

BTW, we use and LOVE Neo!

**Comment by ttempleton** [comment] 2021-01-29 11:43
Looks like this is working fine for me after applying the fix for craftcms/cms#7452, so it will be fixed in the next Craft 3.6 release.

**Closed by ttempleton** 2021-01-29 11:43 UTC

**Comment by denisyilmaz** [comment] 2021-04-29 12:36
the issue appears again in Craft CMS 3.6.12 when Craft CMS is used as a remote Schema with hasura.

**Comment by thinkflo** [comment] 2021-10-01 10:03
@ttempleton Not sure if this is a regression error but I'm getting this using latest versions of Gridsome, CraftCMS, and Embedded Assets.  


```
<page-query>
query CraftEntry ($id: [craft_QueryArgument]) {
  craft {
    entry (id: $id) {
      embeddedAsset {
        image
      }
    }
  }
}
</page-query>   
```
            

```
{
  "errors": [
    {
      "message": "__typename did not match an object type: EmbeddedAsset",
      "stringified": "__typename did not match an object type: EmbeddedAsset\n\nGraphQL request:10:13\n 9 |           ... on craft_videos_Asset {\n10 |             embeddedAsset {\n   |             ^\n11 |               title"
    }
  ],
```
Gridsome Version: 0.7.23
CraftCMS Version: 3.7.14
Embedded Assets Version: 2.8.0

I'm hoping that since this has been solve previously, this is potentially a quick fix.
