### ISSUE TITLE
Some youtube videos are not embedded properly

### ISSUE THREAD

**Issue by piotrpog** [spicywebau/craft-embedded-assets#168] opened 2021-04-03 19:38 UTC
This is link to such example video:
https://www.youtube.com/watch?v=zk-NIBjSyWM

When i try to embed it, i get such result:

![image](https://user-images.githubusercontent.com/42622545/113489506-ec117500-94c4-11eb-88ad-ff9d13468848.png)

The title says "before you go to youtube".

**Comment by ttempleton** [comment] 2021-04-04 02:28
Duplicate of #166, fixed in Embed 3.4.15, which is now set as the minimum Embed version requirement in Embedded Assets 2.5.2.

**Closed by ttempleton** 2021-04-04 02:28 UTC
