### ISSUE TITLE
Problem retrieving data

### ISSUE THREAD

**Issue by sgiraldo** [spicywebau/craft-embedded-assets#87] opened 2018-11-08 13:32 UTC
Hi there,

after a while, I have tried to import a video information through Craft CMS. I have tried several different videos and I have always got a "Could not retrieve embed information" error.  I have not changed anything from the server, but I was thinking it could be related to run withouth ssl protocol. Could it be possible?

Thanks,
Sergi

**Comment by 23d1** [comment] 2018-12-13 04:45
I can confirm the same issue.

**Comment by 23d1** [comment] 2019-02-28 05:47
Issue persists with 2.0.0

**Comment by hiasl** [comment] 2019-03-04 10:19
Same problem here with 2.0.0

**Comment by hiasl** [comment] 2019-03-04 10:58
OK, (at least for my context) I found the solution. Our hosting provider has enabled open_basedir restrictions on the server. Embedded assets (or one of its components) tries to save something to /tmp  directory when retrieving asset information and this is not allowed by this open_basedir restriction. 

By setting the ENV variable TMPDIR in the .env file you can point PHP to a different TMP directory. In our cases, this is a user directory, but I guess pointing it to Craft's storage folder would also be an option.

So all I did was adding a line 
`TMPDIR="/your/path/to/tmp"`
in my .env file.

**Comment by missmatsuko** [comment] 2019-03-12 18:52
Had the same problem and it was also due to a non-writable temp directory.

**Comment by dasunr** [comment] 2019-06-12 02:08
Unrelated to Craft Embedded Assets plugin. Closing ticket.

**Closed by dasunr** 2019-06-12 02:08 UTC
