### ISSUE TITLE
"Before you continue to YouTube" when trying to embed

### ISSUE THREAD

**Issue by Karl456** [spicywebau/craft-embedded-assets#176] opened 2021-05-05 10:05 UTC
#### Description
When trying to embed a video, I get the following preview and the video doesn't work (even after saving)

![image](https://user-images.githubusercontent.com/1711413/117125675-c44a5100-ad91-11eb-95f7-45bbd5034c45.png)

#### Other information
- Embedded Assets version: 2.5.3
- Craft CMS version: 3.6.6

**Comment by ttempleton** [comment] 2021-05-07 09:57
Sounds like a duplicate of #170, which is itself an issue with the Embed library.   Unfortunately there's nothing we can really do about it, other than wait for the pull request to Embed that was mentioned in #170 to be merged and released, and enforce an update to the new version of Embed when it happens.

**Closed by ttempleton** 2021-05-07 09:57 UTC
