### ISSUE TITLE
Embedding youtube videos from EU doesn't work anymore

### ISSUE THREAD

**Issue by ragnarfrosti** [spicywebau/craft-embedded-assets#166] opened 2021-04-01 07:48 UTC
#### Description
Embedding youtube videos from withing the EU seems to not work anymore. When you write in url to a youtube video you get a preview of a Cookies consent page instead of a preview of the video:

<img width="432" alt="Screenshot 2021-04-01 at 09 34 37" src="https://user-images.githubusercontent.com/4622136/113259508-7d1dfb80-92cd-11eb-96b8-f1dff228a04b.png">

This seems to be a stripped version of the following page where you need to accept some cookies settings before being able to view the video

https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYE7VzlLtp-4&gl=SE&m=0&pc=yt&uxe=23983172&hl=en&src=1

<img width="933" alt="Screenshot 2021-04-01 at 09 43 14" src="https://user-images.githubusercontent.com/4622136/113260541-b1de8280-92ce-11eb-9414-275fa2333ce4.png">

If I VPN to US or another country outside the EU the embedding of youtube videos work as before.

**Comment by skoften** [comment] 2021-04-01 08:08
Same issue here.

**Comment by ttempleton** [comment] 2021-04-01 08:27
Likely duplicate of oscarotero/Embed#434 (though I recommend setting up a quick [Embed v3](https://github.com/oscarotero/Embed/tree/v3.x) demo on your server to confirm).  Hopefully this can be resolved on YouTube's end in the near future!

**Closed by ttempleton** 2021-04-01 08:27 UTC

**Comment by skoften** [comment] 2021-04-01 10:15
I just tested it on my server, same issue. 

```
require __DIR__ . '/vendor/autoload.php';

use Embed\Embed;

$info = Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE');

echo $info->title;
echo "\n";
```

Result:

```
fdsfsdn@development:/var/www/test$ php index.php 
Voordat je verdergaat naar YouTube
```

It works with embed/embed version 4 though, but when I upgrade the package, the embedded assets plugin stops working, doesn't load any embed data anymore (from any platform).

**Comment by ttempleton** [comment] 2021-04-01 12:03
Interesting that it worked with Embed v4, but the linked issue mentions it *sometimes* happening, but not reliably, so I'm guessing that's what's happened in that case (and in particular that the reason it might appear to happen more reliably with Embedded Assets is because the plugin caches the embedded asset data).

**Comment by skoften** [comment] 2021-04-01 12:08
We disabled the caching in the code of the plugin, still happening though...

```
    public function requestUrl(string $url): EmbeddedAsset
    {
        $cacheService = Craft::$app->getCache();

        $cacheKey = 'embeddedasset:' . $url;
        $embeddedAsset = $cacheService->get($cacheKey);
		
        $embeddedAsset = false; // disable for now
		
        if (!$embeddedAsset) {
	       
            $pluginSettings = EmbeddedAssets::$plugin->getSettings();
            $array = $this->_getDataFromAdapter($url);
            $embeddedAsset = $this->createEmbeddedAsset($array);

            $cacheService->set($cacheKey, $embeddedAsset, $pluginSettings->cacheDuration);
        }

        return $embeddedAsset;
    }
```

**Comment by ttempleton** [comment] 2021-04-01 12:25
Yep, just noticed the linked issue has been updated to specify that it's happening with v3.

**Comment by kinglozzer** [comment] 2021-04-01 14:07
Hey all, I’ve submitted a pull request to fix this here: https://github.com/oscarotero/Embed/pull/435. Could you test it and verify that it fixes the issue for you too? Thanks!

**Comment by croxton** [comment] 2021-04-01 21:17
Confirmed your latest commit it's working: https://github.com/oscarotero/Embed/pull/436

**Comment by ragnarfrosti** [comment] 2021-04-06 08:54
Thanks for the quick response and fix to this problem 👍
