### ISSUE TITLE
Twitter embeds

### ISSUE THREAD

**Issue by efedorenko** [spicywebau/craft-embedded-assets#234] opened 2023-06-11 20:39 UTC
### Bug Description

I noticed that Twitter embeds have been broken for the last couple weeks. The returned JSON is full of `null`’s.

Is that something that can be fixed or it’s a problem on the Twitter side?

Thank you!

### Steps to reproduce

Embedding [this tweet](https://twitter.com/zander_supafast/status/1666734626784649217):

```
{
    "title": "https://twitter.com/zander_supafast/status/1666734626784649217",
    "description": null,
    "url": "https://twitter.com/zander_supafast/status/1666734626784649217",
    "type": "link",
    "tags": [],
    "feeds": [],
    "images": [],
    "image": null,
    "imageWidth": null,
    "imageHeight": null,
    "code": null,
    "width": null,
    "height": null,
    "aspectRatio": null,
    "authorName": null,
    "authorUrl": null,
    "providerIcons": [
        {
            "url": "https://twitter.com/favicon.ico",
            "width": 16,
            "height": 16,
            "size": 256,
            "mime": "image/x-icon"
        },
        {
            "url": "https://abs.twimg.com/favicons/twitter.2.ico",
            "width": 32,
            "height": 32,
            "size": 1024,
            "mime": "image/vnd.microsoft.icon"
        },
        {
            "url": "https://abs.twimg.com/responsive-web/client-web-legacy/icon-ios.b1fc727a.png",
            "width": 1024,
            "height": 1024,
            "size": 1048576,
            "mime": "image/png"
        }
    ],
    "providerIcon": "https://abs.twimg.com/responsive-web/client-web-legacy/icon-ios.b1fc727a.png",
    "providerName": "Twitter",
    "providerUrl": "https://twitter.com",
    "publishedTime": null,
    "license": null
}
```

### Embedded Assets version

2.11.4

### Craft CMS version

3.8.11

**Comment by ttempleton** [comment] 2023-06-13 07:59
I'm going to close this as a duplicate of https://github.com/oscarotero/Embed/issues/518 since this plugin uses that package to get embed data - although the speculation on that issue is that it's on Twitter's end.

**Closed by ttempleton** 2023-06-13 07:59 UTC
Labels: bug
