### ISSUE TITLE
2.0 Install error

### ISSUE THREAD

**Issue by laurabennett** [spicywebau/craft-embedded-assets#96] opened 2019-02-26 16:49 UTC
#### Description
Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package benjamminf/craft-embedded-assets 2.0.0 exists as benjamminf/craft-embedded-assets[1.0.2] but these are rejected by your constraint.
Problem 2
- The requested package benjamminf/craft-embedded-assets (locked at 1.0.2, required as 2.0.0) is satisfiable by benjamminf/craft-embedded-assets[1.0.2] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

#### Steps to reproduce
I tried upgrading from the previous version of Embedded Assets and when that failed I uninstalled and then tried installing the latest version but still get the error.  Once I removed the 1.2 version completely I was then finally able to install 2.0.  This is certainly not an ideal upgrade workflow.

#### Other information
- Craft CMS version: 3.1.14

**Comment by ttempleton** [comment] 2019-02-26 22:18
Updating Embedded Assets through the Craft control panel does appear to fail; the update process tries to update the old package `benjamminf/craft-embedded-assets` to 2.0.0.  I'm honestly not sure whether that would be a bug in Craft or the expected behaviour -- the plugin store does list the new package name `spicyweb/craft-embedded-assets`, but should Craft be expected to check that for every update just for a rare case like this -- but in any case, because the failed update process would have updated Craft's `composer.json`, the old package's version requirement would need to be corrected to 1.0.2 before any further updating or installing of the new Embedded Assets package would work.

We're going to close this issue at this point; we believe that this would happen in any case where a plugin changes ownership and its package name changes, so it's not an issue with Embedded Assets, strictly speaking.  We'll consider revising the alert in the changelog, though, to note that the new package should be installed from a terminal rather than through Craft.

**Closed by ttempleton** 2019-02-26 22:18 UTC
Labels: invalid

**Comment by olets** [comment] 2019-03-08 19:43
@ttempleton to be clear, is your recommended migration path

```
composer remove benjamminf/craft-embedded-assets
composer require spicyweb/craft-embedded-assets
```

?

**Comment by ttempleton** [comment] 2019-03-09 04:51
@olets We recommend running `composer require spicyweb/craft-embedded-assets` before `composer remove benjamminf/craft-embedded-assets`, just so an Embedded Assets plugin of some kind exists in the project at all times (there shouldn't be any conflicts during the brief time that both packages are included in the project).  But if the update process through the Craft control panel has previously been attempted and failed, then the project's `composer.json` will need to be checked to ensure that the required version for `benjamminf/craft-embedded-assets` is 1.0.2 before proceeding with the two commands.
